name: Daily Order Status Updater

on:
  schedule:
    - cron: '00 8 * * *'  # 每天 UTC 時間 04:00，對應台北時間 14:30
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Render (optional)
        run: curl https://demo-pawpawplanet-backend.onrender.com/api/scheduler/ping

      - name: Wait for Render to wake up
        run: sleep 55  # 等 55 秒（確保 Render 已啟動）

      - name: Call close-due-orders API
        run: |
          curl -X POST https://demo-pawpawplanet-backend.onrender.com/api/scheduler/close-due-orders \
            -H "Authorization: Bearer ${{ secrets.SCHEDULER_SECRET }}"